export const ACCESS_CREATE_REQUEST = 'ACCESS_CREATE_REQUEST'
export const ACCESS_CREATE_SUCCESS = 'ACCESS_CREATE_SUCCESS'
export const ACCESS_CREATE_FAIL = 'ACCESS_CREATE_FAIL'
export const ACCESS_CREATE_RESET = 'ACCESS_CREATE_RESET'

export const ACCESS_LIST_BY_CREATOR_REQUEST  = 'ACCESS_LIST_BY_CREATOR_REQUEST'
export const ACCESS_LIST_BY_CREATOR_SUCCESS = 'ACCESS_LIST_BY_CREATOR_SUCCESS'
export const ACCESS_LIST_BY_CREATOR_FAIL = 'ACCESS_LIST_BY_CREATOR_FAIL'
export const ACCESS_LIST_BY_CREATOR_RESET = 'ACCESS_LIST_BY_CREATOR_RESET'