export const ACCESS_CREATE_REQUEST = 'ACCESS_CREATE_REQUEST'
export const ACCESS_CREATE_SUCCESS = 'ACCESS_CREATE_SUCCESS'
export const ACCESS_CREATE_FAIL = 'ACCESS_CREATE_FAIL'
export const ACCESS_CREATE_RESET = 'ACCESS_CREATE_RESET'

export const ACCESS_LIST_BY_CREATOR_REQUEST  = 'ACCESS_LIST_BY_CREATOR_REQUEST'
export const ACCESS_LIST_BY_CREATOR_SUCCESS = 'ACCESS_LIST_BY_CREATOR_SUCCESS'
export const ACCESS_LIST_BY_CREATOR_FAIL = 'ACCESS_LIST_BY_CREATOR_FAIL'
export const ACCESS_LIST_BY_CREATOR_RESET = 'ACCESS_LIST_BY_CREATOR_RESET'

export const ACCESS_DETAILS_REQUEST  = 'ACCESS_DETAILS_REQUEST'
export const ACCESS_DETAILS_SUCCESS = 'ACCESS_DETAILS_SUCCESS'
export const ACCESS_DETAILS_FAIL = 'ACCESS_DETAILS_FAIL'

export const ACCESS_UPDATE_REQUEST  = 'ACCESS_UPDATE_REQUEST'
export const ACCESS_UPDATE_SUCCESS = 'ACCESS_UPDATE_SUCCESS'
export const ACCESS_UPDATE_FAIL = 'ACCESS_UPDATE_FAIL'
export const ACCESS_UPDATE_RESET = 'ACCESS_UPDATE_RESET'

export const ACCESS_DELETE_REQUEST  = 'ACCESS_DELETE_REQUEST'
export const ACCESS_DELETE_SUCCESS = 'ACCESS_DELETE_SUCCESS'
export const ACCESS_DELETE_FAIL = 'ACCESS_DELETE_FAIL'
export const ACCESS_DELETE_RESET = 'ACCESS_DELETE_RESET'