export const CHECKOUT_CREATE_REQUEST = 'CHECKOUT_CREATE_REQUEST'
export const CHECKOUT_CREATE_SUCCESS = 'CHECKOUT_CREATE_SUCCESS'
export const CHECKOUT_CREATE_FAIL = 'CHECKOUT_CREATE_FAIL'
export const CHECKOUT_CREATE_RESET = 'CHECKOUT_CREATE_RESET'
