export const EMAIL_SUPPORT_CREATE_REQUEST = 'EMAIL_SUPPORT_CREATE_REQUEST'
export const EMAIL_SUPPORT_CREATE_SUCCESS = 'EMAIL_SUPPORT_CREATE_SUCCESS'
export const EMAIL_SUPPORT_CREATE_FAIL = 'EMAIL_SUPPORT_CREATE_FAIL'
export const EMAIL_SUPPORT_CREATE_RESET = 'EMAIL_SUPPORT_CREATE_RESET'

export const EMAIL_SUPPORT_LIST_REQUEST = 'EMAIL_SUPPORT_LIST_REQUEST'
export const EMAIL_SUPPORT_LIST_SUCCESS = 'EMAIL_SUPPORT_LIST_SUCCESS'
export const EMAIL_SUPPORT_LIST_FAIL = 'EMAIL_SUPPORT_LIST_FAIL'