export const PAYMENTPLAN_LIST_REQUEST = 'PAYMENTPLAN_LIST_REQUEST'
export const PAYMENTPLAN_LIST_SUCCESS = 'PAYMENTPLAN_LIST_SUCCESS'
export const PAYMENTPLAN_LIST_FAIL = 'PAYMENTPLAN_LIST_FAIL'

export const PAYMENTPLAN_UPDATE_REQUEST = 'PAYMENTPLAN_UPDATE_REQUEST'
export const PAYMENTPLAN_UPDATE_SUCCESS = 'PAYMENTPLAN_UPDATE_SUCCESS'
export const PAYMENTPLAN_DETAILS_SUCCESS = 'PAYMENTPLAN_DETAILS_SUCCESS'
export const PAYMENTPLAN_UPDATE_FAIL = 'PAYMENTPLAN_UPDATE_FAIL'

