export const PAYMENTPLAN_LIST_REQUEST = 'PAYMENTPLAN_LIST_REQUEST'
export const PAYMENTPLAN_LIST_SUCCESS = 'PAYMENTPLAN_LIST_SUCCESS'
export const PAYMENTPLAN_LIST_FAIL = 'PAYMENTPLAN_LIST_FAIL'

export const PAYMENTPLAN_UPDATE_REQUEST = 'PAYMENTPLAN_UPDATE_REQUEST'
export const PAYMENTPLAN_UPDATE_SUCCESS = 'PAYMENTPLAN_UPDATE_SUCCESS'
export const PAYMENTPLAN_DETAILS_SUCCESS = 'PAYMENTPLAN_DETAILS_SUCCESS'
export const PAYMENTPLAN_UPDATE_FAIL = 'PAYMENTPLAN_UPDATE_FAIL'

export const PAYMENTPLAN_DELETE_REQUEST = 'PAYMENTPLAN_DELETE_REQUEST'
export const PAYMENTPLAN_DELETE_SUCCESS = 'PAYMENTPLAN_DELETE_SUCCESS'
export const PAYMENTPLAN_DELETE_FAIL = 'PAYMENTPLAN_DELETE_FAIL'
export const PAYMENTPLAN_UPDATE_RESET = 'PAYMENTPLAN_UPDATE_RESET'


export const PAYMENTPLAN_CREATE_REQUEST = 'PAYMENTPLAN_CREATE_REQUEST'
export const PAYMENTPLAN_CREATE_SUCCESS = 'PAYMENTPLAN_CREATE_SUCCESS'
export const PAYMENTPLAN_CREATE_FAIL = 'PAYMENTPLAN_CREATE_FAIL'


 
 

