export const SUPPORT_LIST_REQUEST = 'SUPPORT_LIST_REQUEST'
export const SUPPORT_LIST_SUCCESS = 'SUPPORT_LIST_SUCCESS'
export const SUPPORT_LIST_FAIL = 'SUPPORT_LIST_FAIL'

export const SUPPORT_DETAILS_REQUEST = 'SUPPORT_DETAILS_REQUEST'
export const SUPPORT_DETAILS_SUCCESS = 'SUPPORT_DETAILS_SUCCESS'
export const SUPPORT_DETAILS_FAIL = 'SUPPORT_DETAILS_FAIL'



