export const KNOWLEDGE_BASE_CREATE_REQUEST = 'KNOWLEDGE_BASE_CREATE_REQUEST'
export const KNOWLEDGE_BASE_CREATE_SUCCESS = 'KNOWLEDGE_BASE_CREATE_SUCCESS'
export const KNOWLEDGE_BASE_CREATE_FAIL = 'KNOWLEDGE_BASE_CREATE_FAIL'
export const KNOWLEDGE_BASE_CREATE_RESET = 'KNOWLEDGE_BASE_CREATE_RESET'

export const KNOWLEDGE_BASE_LIST_REQUEST = 'KNOWLEDGE_BASE_LIST_REQUEST'
export const KNOWLEDGE_BASE_LIST_SUCCESS = 'KNOWLEDGE_BASE_LIST_SUCCESS'
export const KNOWLEDGE_BASE_LIST_FAIL = 'KNOWLEDGE_BASE_LIST_FAIL'

export const KNOWLEDGE_BASE_UPDATE_REQUEST = 'KNOWLEDGE_BASE_UPDATE_REQUEST'
export const KNOWLEDGE_BASE_UPDATE_SUCCESS = 'KNOWLEDGE_BASE_UPDATE_SUCCESS'
export const KNOWLEDGE_BASE_UPDATE_FAIL = 'KNOWLEDGE_BASE_UPDATE_FAIL'
export const KNOWLEDGE_BASE_UPDATE_RESET = 'KNOWLEDGE_BASE_UPDATE_RESET'

export const KNOWLEDGE_BASE_DETAILS_REQUEST  = 'KNOWLEDGE_BASE_DETAILS_REQUEST'
export const KNOWLEDGE_BASE_DETAILS_SUCCESS = 'KNOWLEDGE_BASE_DETAILS_SUCCESS'
export const KNOWLEDGE_BASE_DETAILS_FAIL = 'KNOWLEDGE_BASE_DETAILS_FAIL'


export const KNOWLEDGE_BASE_DELETE_REQUEST  = 'KNOWLEDGE_BASE_DELETE_REQUEST'
export const KNOWLEDGE_BASE_DELETE_SUCCESS = 'KNOWLEDGE_BASE_DELETE_SUCCESS'
export const KNOWLEDGE_BASE_DELETE_FAIL = 'KNOWLEDGE_BASE_DELETE_FAIL'

